### ISSUE TITLE
Fallback-mount с джинглом, перенаправление на который при пропаже связи

### ISSUE THREAD

**Issue by ridouchire** [nesorter/nesorter#11]
Icecast умеет при пропаже потока на основном маунте фоллбечить на другой. А также умеет проигрывать там по кругу один фаел без сурс-клиента. 

Надо это всё соединить, и играть некий джингл при пропаже потока. Например, в полночь. 
А также обеспечить обратный переход при возникновении потока на основном маунте.

**Comment by ridouchire** [comment]
Изначально я думал, что сурс-клиент уходит с маунта, но в итоге у нас просто в потоке тишина. Если следовать изначальному условию задачи, то она невыполнима.

**Comment by kugimiya** [comment]
@ridouchire тоже так думаю. Вообще, есть у меня мысль, при опустошении queue запускать хотя бы что-то на воспроизведение, хоть музыку из лифта. Это, наверно, и сделаю.
