### ISSUE TITLE
В инструкции по разворачиванию пропущен шаг

### ISSUE THREAD

**Issue by ridouchire** [nesorter/nesorter#9]
В инструкции по разворачиванию пропущен шаг, где пример файла окружения по пути `srv/env.example` необходимо скопировать в `srv/.env`. В противном случае сервис *api* не будет собран.

**Comment by kugimiya** [comment]
Расширил: https://github.com/nesorter/nesorter/blob/main/README.md#%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D0%B2-docker

Теперь норм?
